import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { caseStudies } from '../data';
const previewCases = caseStudies.slice(0, 3);
export default function CallToAction() {
    const { t } = useTranslation();
    return (_jsxs(_Fragment, { children: [_jsx("section", { className: "py-16 md:py-20", children: _jsxs("div", { className: "container-x", children: [_jsxs("div", { className: "text-center mb-14", children: [_jsx("p", { className: "section-eyebrow mb-3", children: t('home.cases.eyebrow') }), _jsx("h2", { className: "section-title", children: t('home.cases.title') })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6 mb-10", children: previewCases.map((c) => (_jsxs(Link, { to: "/cases", className: "card overflow-hidden group", children: [_jsx("div", { className: "aspect-[16/10] overflow-hidden bg-ink-100", children: _jsx("img", { src: c.cover, alt: c.title, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" }) }), _jsxs("div", { className: "p-5", children: [_jsx("p", { className: "text-xs font-semibold text-brand-600 uppercase tracking-wider mb-2", children: c.industry }), _jsx("h3", { className: "font-semibold text-ink-900 mb-2", children: c.title }), _jsx("p", { className: "text-sm text-ink-500 line-clamp-2", children: c.description })] })] }, c.slug))) }), _jsx("div", { className: "text-center", children: _jsx(Link, { to: "/cases", className: "btn-outline", children: t('home.cases.viewAll') }) })] }) }), _jsx("section", { className: "py-16 bg-gradient-to-r from-brand-700 to-brand-600 text-white", children: _jsxs("div", { className: "container-x flex flex-col md:flex-row items-center justify-between gap-6", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-2xl md:text-3xl font-bold", children: t('home.cta.title') }), _jsx("p", { className: "mt-2 text-brand-100", children: t('home.cta.desc') })] }), _jsx(Link, { to: "/contact", className: "btn-primary !bg-white !text-brand-700 hover:!bg-brand-50", children: t('home.cta.button') })] }) })] }));
}
